# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82da25b77345ce92dc2de65bf9404acab9eeac6db9b93ac01f4c686084ecb276550d600a820c38bfd3efed884aab9935aaac4861473e2a8c43ea4825f89fdb48

test:
  secret_key_base: 62d9250208653f3929f38b25f6921dea3660e28db821131b0f42b1dc5f81d92bf1a0e2cdfbaef6be0261b11f15b11dc2c3713b66ac50f9fa33834d70a4654e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
